name: node application with build, unit testing and lint check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm       # or ~/.yarn/cache if using Yarn
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node install
        run: npm i

      - name: lint check
        id: lint_check
        continue-on-error: true
        run: npm run lint

      - name: Auto-fix ESLint errors if failed (step 2)
        if: steps.lint_check.outcome == 'failure'
        run: npx eslint . --fix

      - name: Re-run ESLint check after fix (step 3)
        if: steps.lint_check.outcome == 'failure'
        run: npm run lint

  build-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Node environment setup
        uses: actions/setup-node@v4
        with:
            node-version: 20
            
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: intial tailwindcss
        run: |
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: public/css/style.css 
      
      - name: Build and push frontend image
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }}:${{ env.TIMESTAMP }} -t ${{ env.FRONTEND_IMAGE }}:latest ./log-reg-Client
          docker push ${{ env.FRONTEND_IMAGE }}:${{ env.TIMESTAMP }}
          docker push ${{ env.FRONTEND_IMAGE }}:latest
      
        env:
          REGISTRY: ghcr.io
          FRONTEND_IMAGE: ghcr.io/Akila1996522/todo
          TIMESTAMP: ${{ github.run_number }}-${{ github.sha }}
  
  deploy:
    needs: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_KNOWN_HOSTS }} << 'EOF'
            sudo su
            if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
              cd /var/www/todo/
            else
              cd /var/www/dev.damselbiz.com/
            fi
            docker compose down
            docker image prune -af
            docker compose pull
            docker compose up -d
          EOF
        shell: bash
    env:
      deploy_path: ${{ vars.deploy-path }}
      